<?php

/**
 * @file
 * Node Edit Link hooks and alters.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function node_edit_link_node_access(NodeInterface $node, $operation, AccountInterface $account) {
  return AccessResult::allowedIf($operation == 'update' && \Drupal::service('node_edit_link.csrf')->checkAccess($node));
}

/**
 * Implements hook_entity_form_mode_alter().
 */
function node_edit_link_entity_form_mode_alter(&$form_mode, EntityInterface $entity) {
  if (
    $entity instanceof NodeInterface &&
    \Drupal::service('node_edit_link.csrf')->checkAccess($entity)
  ) {
    $form_mode = 'edit_link';
  }
}

/**
 * Implements hook_form_alter().
 */
function node_edit_link_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('node_edit_link.csrf')->addFormElements($form, $form_state);
}
